ROOT/ROOT/urls.py
from api import urls as api_urls
from datenschleuder import urls as datenschleuder_urls
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from import_app import urls as import_app_urls
from members import urls as members_urls
from other import urls as other_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^members/', include('members.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^import_app/', include('import_app.urls')),
    url(r'^datenschleuder/', include('datenschleuder.urls')),
    url(r'', include(other_urls)),
]

urlpatterns += staticfiles_urlpatterns()

ROOT/api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^mail_send_next/', views.mail_send_next, name='mail_send_next'),
    url(r'^mail_send_all/', views.mail_send_all, name='mail_send_all'),
    url(r'^mail_create/', views.mail_create, name='mail_create'),
    url(r'^mail_still_to_send/', views.mail_still_to_send, name='mail_still_to_send'),
    url(r'^billing_cycle/', views.billing_cycle, name='billing_cycle'),
    url(r'^member_info/', views.member_info, name='member_info'),
    url(r'^zip_analysis/', views.zip_analysis, name='zip_analysis'),
    url(r'^country_analysis/', views.country_analysis, name='country_analysis'),
    url(r'^search_member_db/', views.search_member_db, name='search_member_db'),
    url(r'^get_erfa_statistics/', views.get_erfa_statistics, name='get_erfa_statistics'),
    url(r'^drop_transactions/', views.drop_transactions, name='drop_transactions'),
    url(r'^address_unknown/', views.bulk_address_unknown, name='api_bulk_address_unknown'),
    url(r'^send_data_record/', views.member_queue_data_record_email, name='send_data_record'),
    url(r'^member_inactivate/', views.member_inactivate, name='member_inactivate'),
    url(r'^member_reactivate/', views.member_reactivate, name='member_reactivate'),
]

ROOT/members/urls.py
from django.conf.urls import url

from . import views

app_name = 'members'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^import_members/', views.run_import_members, name='import_members'),
    url(r'^add_member/', views.add_member, name='add_member'),
    url(r'^delete_emails/', views.delete_emails, name='delete_emails'),
    url(r'^search_form/', views.search_member_db, name='search_form'),
    url(r'^member_address_unknown/', views.member_address_unknown, name='memberAddressUnknown'),

    url(r'^statistics/monthly/', views.monthly_statistics, name='monthly_statistics'),
    url(r'^statistics/overview/', views.general_statistics, name='general_statistics'),

    url(r'^erfaabgleich/export/(?P<all_erfas>all)?', views.erfaabgleich_export, name='erfaabgleich_export'),
    url(r'^erfaabgleich/import/(?P<all_erfas>all)?', views.erfaabgleich_import, name='erfaabgleich_import'),
    url(r'^erfaabgleich/cashpoint_export/', views.cashpoint_export, name='cashpoint_export'),
    url(r'^erfaabgleich/vereinstisch_import/', views.vereinstisch_import, name='vereinstisch_import'),
    url(r'^erfaabgleich/vereinstisch_export/', views.vereinstisch_export, name='vereinstisch_export'),
    url(r'^erfaabgleich/', views.erfaabgleich, name='erfaabgleich'),
    url(r'^show_transaction_log/$', views.show_transaction_log, name='show_transaction_log'),
    url(r'^show_transaction_log/(\d+)$', views.show_transaction_log, name='show_member_transaction_log'),
    url(r'^anti_transaction/(\d+)$', views.anti_transaction, name='anti_transaction'),
    url(r'^erfa/(?P<erfa>\d+)$', views.ErfaListView.as_view(template_name='member_list.html'), name='erfa'),
    url(r'^select_erfa/$', views.erfa_select_form, name='select_erfa'),
]

ROOT/other/urls.py
from django.conf.urls import url
from other import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

ROOT/other/views.py
from django.conf import settings
from django.shortcuts import render


def index(request):
    hasDatenschleuder = 'datenschleuder' in settings.INSTALLED_APPS
    return render(request, "index_other.html", {'hasDatenschleuder': hasDatenschleuder})

ROOT/other/templates/head_defaults.html
{% load staticfiles %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>

<link rel="stylesheet" href="{% static 'bootstrap-3.3.6-dist/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'bootstrap-3.3.6-dist/css/bootstrap-theme.min.css' %}">

<!-- Latest compiled and minified JavaScript -->
<script src="{% static 'bootstrap-3.3.6-dist/js/bootstrap.min.js' %}"></script>

ROOT/other/templates/index_other.html
<!DOCTYPE html>
<html lang="de">
    <head>
        {% load staticfiles %}
        {% include "head_defaults.html" %}
        <title>Association Administration</title>
        <style>
            .btn-block+.btn-block {
                margin-top: 23px;
            }
        </style>
    </head>
    <body>
        <div class="page-header">
            <h1>Administration Association</h1>
        </div>

        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <a class="btn btn-primary btn-lg btn-block" href="{% url 'members:add_member' %}">ADD Members</a>
                <a class="btn btn-primary btn-lg btn-block" href="{% url 'members:index' %}">Member Interaction</a>
                <a class="btn btn-primary btn-lg btn-block" href="{% url 'members:erfaabgleich' %}">Erfa Abgleich</a>
                <a class="btn btn-primary btn-lg btn-block" href="/import_app/import_banking_csv">Import Banking</a>
                <a class="btn btn-primary btn-lg btn-block" href="/admin">DB-Admin</a>
                {% if hasDatenschleuder %}
                    <a class="btn btn-primary btn-lg btn-block" href="/admin/datenschleuder">Datenschleuder</a>
                {% endif %}
            </div>
            <div class="col-md-4"></div>
        </div>
    </body>
</html>