ROOT/ROOT/urls.py
from api import urls as api_urls
from datenschleuder import urls as datenschleuder_urls
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from import_app import urls as import_app_urls
from members import urls as members_urls
from other import urls as other_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^members/', include('members.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^import_app/', include('import_app.urls')),
    url(r'^datenschleuder/', include('datenschleuder.urls')),
    url(r'', include(other_urls)),
]

urlpatterns += staticfiles_urlpatterns()

ROOT/api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^mail_send_next/', views.mail_send_next, name='mail_send_next'),
    url(r'^mail_send_all/', views.mail_send_all, name='mail_send_all'),
    url(r'^mail_create/', views.mail_create, name='mail_create'),
    url(r'^mail_still_to_send/', views.mail_still_to_send, name='mail_still_to_send'),
    url(r'^billing_cycle/', views.billing_cycle, name='billing_cycle'),
    url(r'^member_info/', views.member_info, name='member_info'),
    url(r'^zip_analysis/', views.zip_analysis, name='zip_analysis'),
    url(r'^country_analysis/', views.country_analysis, name='country_analysis'),
    url(r'^search_member_db/', views.search_member_db, name='search_member_db'),
    url(r'^get_erfa_statistics/', views.get_erfa_statistics, name='get_erfa_statistics'),
    url(r'^drop_transactions/', views.drop_transactions, name='drop_transactions'),
    url(r'^address_unknown/', views.bulk_address_unknown, name='api_bulk_address_unknown'),
    url(r'^send_data_record/', views.member_queue_data_record_email, name='send_data_record'),
    url(r'^member_inactivate/', views.member_inactivate, name='member_inactivate'),
    url(r'^member_reactivate/', views.member_reactivate, name='member_reactivate'),
]

ROOT/import_app/urls.py
from django.conf.urls import url

from . import views

app_name = 'import_app'

urlpatterns = [
    url(r'^import_banking_csv/', views.run_import_banking, name='import_banking'),
    url(r'^manage_transactions/', views.manage_transactions, name='manage_transactions'),
    url(r'^manage_transactions_failed/', views.manage_transactions_failed, name='manage_transactions_failed'),
    url(r'^manage_transactions_confirm/', views.manage_transactions_confirm, name='manage_transactions_confirm'),
    url(r'^manage_transactions_book/', views.manage_transactions_book, name='manage_transactions_book'),
    url(r'^member_lookup/(\d+)', views.member_lookup, name='member_lookup'),
]

ROOT/import_app/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

import csv
import datetime
import json
import logging

from django.conf import settings
from django.db import IntegrityError, models
from import_app.csv_parser import TransactionReader
from members.models import BalanceTransactionLog, Member

logging.getLogger(__name__)
logging.getLogger().setLevel(logging.INFO)


class Transaction(models.Model):
    RATING_BAD = 64
    NO_CHAOS_NUMBER = -1111

    STATUS_MATCHED_CHAOS_NR = 'M'
    STATUS_UNKNOWN_CHAOS_NR = 'U'
    STATUS_COMPLETED = 'C'
    STATUS_IGNOREFOREVER = 'I'
    STATUS_FAILED = 'F'
    # code blaming: symbols on classes _pending [fixed]
    STATUS_OPTIONS = ((STATUS_MATCHED_CHAOS_NR, 'matched chaos nr'),
                      (STATUS_UNKNOWN_CHAOS_NR, 'unknown chaos nr'),
                      (STATUS_COMPLETED, 'completed'),
                      (STATUS_IGNOREFOREVER, 'ignore forever'),
                      (STATUS_FAILED, 'failed at booking'))
    string_in = models.CharField(max_length=1000, unique=True)
    booking_day = models.DateField(null=False, default=datetime.date.today)
    available_on = models.DateField(null=False, default=datetime.date.today)
    payment_type = models.CharField(max_length=80)
    information = models.TextField()
    referenz = models.TextField()
    verwendungszweck = models.TextField()
    payer = models.CharField(max_length=80)
    payee = models.CharField(max_length=80)
    amount = models.IntegerField()
    balance = models.IntegerField()
    chaos_number = models.IntegerField()
    chaosnr_options = models.CharField(max_length=200, blank=True, null=True)
    rating = models.PositiveSmallIntegerField()
    status = models.CharField(max_length=1, choices=STATUS_OPTIONS)

    def handle_chaos_nr_error(self):
        self.rating = Transaction.RATING_BAD
        logging.warning("pre wipe chaos number {}".format(self.chaos_number))
        self.chaos_number = Transaction.NO_CHAOS_NUMBER
        if self.status == self.STATUS_MATCHED_CHAOS_NR:
            self.status = self.STATUS_UNKNOWN_CHAOS_NR

    def add_transaction(self, transaction_reader, threshold=15, max_chaos_nr=pow(2, 63) - 1):
        # TODO: check for addition of identical transactions (transaction ID? whole entry?)
        if not isinstance(transaction_reader, TransactionReader):
            raise ValueError()
        transaction_fields = self._meta.get_fields()
        transaction_fields = [x.name for x in transaction_fields]
        shared_keys = set(transaction_fields) & set(transaction_reader.__dict__.keys())
        shared_keys.remove('chaos_number')
        if transaction_reader.amount <= 0:
            raise NegativeCreditError
        for key in shared_keys:
            setattr(self, key, getattr(transaction_reader, key))

        try:
            if int(transaction_reader.chaos_number[0]) <= max_chaos_nr:
                self.chaos_number = int(transaction_reader.chaos_number[0])
            else:
                self.handle_chaos_nr_error()
            self.chaosnr_options = json.dumps(transaction_reader.chaos_number[1:])
        except ValueError as e:
            logging.warning("Value Error {}".format(e))
            self.handle_chaos_nr_error()
        except TypeError as e:
            logging.warning("Type Error {}".format(e))
            self.handle_chaos_nr_error()
        except IndexError as e:
            logging.warning("Index Error {}".format(e))
            self.handle_chaos_nr_error()

        if transaction_reader.donation:
            self.status = self.STATUS_IGNOREFOREVER
        elif self.rating < threshold:
            self.status = self.STATUS_MATCHED_CHAOS_NR
        else:
            self.status = self.STATUS_UNKNOWN_CHAOS_NR
        try:
            self.save()
        except IntegrityError as e:
            logging.warning('db integrity constraint failed, unique transaction for: {}\n{}?'.format(self.chaos_number, e))
            raise DuplicateBankingWarning

    def __str__(self):
        return str(self.chaos_number)

    def book(self):
        if not self.status == Transaction.STATUS_MATCHED_CHAOS_NR:
            raise TransactionNotPendingError
        try:
            mem_match = Member.objects.get(pk=self.chaos_number)
            mem_match.increase_balance_by(increase_by=self.amount,
                                          reason=BalanceTransactionLog.IMPORT_BANKING,
                                          comment=self.information,
                                          booking_day=self.booking_day,
                                          bank_transaction=self)
            self.status = Transaction.STATUS_COMPLETED
        except Exception as e:
            self.status = Transaction.STATUS_FAILED
            logging.warning(e)
        self.save()

    def get_expected_member(self):
        return Member.objects.get(pk=self.chaos_number)


class TransactionNotPendingError(Exception):
    pass


class DuplicateBankingWarning(Warning):
    pass


class NegativeCreditError(Exception):
    pass

# TODO: discard 'Spende' & fee transactions that cannot be resolved

# TODO: Exception on Doppelmitgliedschaft and individual payment
# TODO: dont accept payment when membership end date set


def pseudotest():
    csv_in = open("../testdata/PB_Umsatzauskunft_KtoNr0599090201_01-08-2015_2007.csv", encoding="iso-8859-1").readlines()
    csv_in = csv.reader(csv_in, delimiter=';')
    for item in csv_in:
        print("---")
        if len(item) == 8:
            tr = TransactionReader(item)
            if tr.income:
                try:
                    new_tr = Transaction()
                    new_tr.add_transaction(tr)
                except Exception as e:
                    print(e)


# TODO: import app: (multiline)
# name anzeigen
# lower confidence at least for present year
# pagination!!
# pending for every number after a key
# lower confidence for back2back numbers e.g. chaos nr. 123 4
# vergleich mit datenbank before manual checking
# comment field zu 1024
# spende raus/third color?
# will be paid until
# status ausblenden (failed/completed)
# umnennen erroneous -> unknown, pending -> match
# clean up debug output
# linking in with navigation
# failed transactions wieder anzeigen (by 'OK')

ROOT/import_app/views.py
import csv
import io
import logging

import import_app.csv_parser as csv_parser
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.forms import modelformset_factory
from django.http import JsonResponse
from django.shortcuts import render
from import_app.forms_import import BankingImportForm
from members.models import Member

from .models import DuplicateBankingWarning, NegativeCreditError, Transaction

logging.getLogger(__name__)
logging.getLogger().setLevel(logging.INFO)


def run_import_banking(request):
    # Handle file upload
    uploadedFile = ''
    errors = []
    imported = []
    context = {}
    if request.method == 'POST':
        form = BankingImportForm(request.POST, request.FILES)
        if form.is_valid():
            uploadedFile = request.FILES['docfile']
            data = uploadedFile.read().decode("iso-8859-1")
            f = io.StringIO(data)
            reader = csv.reader(f, delimiter=';')
            duplicate_warnings = []
            for row in reader:
                logging.debug("reading row: {}".format(row))
                if len(row) == 8 and not row[0].startswith('Buchungstag'):
                    new_transaction = csv_parser.TransactionReader(row)
                    new_tr_entry = Transaction()
                    try:
                        new_tr_entry.add_transaction(new_transaction)
                    except DuplicateBankingWarning:
                        duplicate_warnings.append('Duplicated entry not added: {}'.format(new_tr_entry.string_in))
                    except NegativeCreditError:
                        logging.info("Outgoing transaction skipped")
            if len(duplicate_warnings) > 0:
                context["warnings"] = duplicate_warnings
            context["message"] = "uploaded successfully"

    form = BankingImportForm()  # A empty, unbound form
    context.update({'form': form, 'uploadedFile': uploadedFile, 'errors': errors, 'imported': imported})
    logging.info("context is {}".format(context))
    return render(request, 'import_banking_csv.html', context)


def manage_transactions_failed(request):
    """ show and manage failed transactions"""
    TransactionFormSet = modelformset_factory(Transaction, fields=('chaos_number', 'status'), extra=0)
    logging.info("manage_transactions: TransactionFormset".format(TransactionFormSet))
    if request.method == 'POST':
        formset = TransactionFormSet(request.POST, request.FILES)
        filteredformset = TransactionFormSet()
        if formset.is_valid():
            formset.save()
            logging.info("TMP {}".format(formset))
            return render(
                request,
                "manage_transactions_confirm.html",
                context={
                    "formset": formset,
                    "status_matching": Transaction.STATUS_MATCHED_CHAOS_NR,
                    "status_erroneous": Transaction.STATUS_FAILED,
                },
            )

    else:
        # pagination goes here
        qs = Transaction.objects.filter(status=Transaction.STATUS_FAILED)
        paginator = Paginator(qs, 10)
        page = request.GET.get('page')
        try:
            objects = paginator.page(page)
        except PageNotAnInteger:
            objects = paginator.page(1)
        except EmptyPage:
            objects = paginator.page(paginator.num_pages)

        page_query = qs.filter(id__in=[object.id for object in objects])
        formset = TransactionFormSet(queryset=page_query)
        context = {'objects': objects, 'formset': formset, "status_matching": Transaction.STATUS_MATCHED_CHAOS_NR}
        return render(request, 'manage_transactions.html', context)


def manage_transactions(request):
    TransactionFormSet = modelformset_factory(Transaction, fields=('chaos_number', 'status'), extra=0)
    logging.info("manage_transactions: TransactionFormset".format(TransactionFormSet))
    if request.method == 'POST':
        formset = TransactionFormSet(request.POST, request.FILES)
        if formset.is_valid():
            formset.save()
            logging.info("TMP {}".format(formset))
            return render(template_name="manage_transactions_confirm.html",
                          context={"formset": formset,
                                   "status_matching": Transaction.STATUS_MATCHED_CHAOS_NR,
                                   "status_erroneous": Transaction.STATUS_UNKNOWN_CHAOS_NR,
                                   }, request=request)

    # pagination goes here
    qs = Transaction.objects.filter(status=Transaction.STATUS_UNKNOWN_CHAOS_NR)\
        | Transaction.objects.filter(status=Transaction.STATUS_MATCHED_CHAOS_NR)
    paginator = Paginator(qs, 10)
    page = request.GET.get('page')
    try:
        objects = paginator.page(page)
    except PageNotAnInteger:
        objects = paginator.page(1)
    except EmptyPage:
        objects = paginator.page(paginator.num_pages)

    page_query = qs.filter(id__in=[obj.id for obj in objects])
    formset = TransactionFormSet(queryset=page_query)
    context = {'objects': objects, 'formset': formset, "status_matching": Transaction.STATUS_MATCHED_CHAOS_NR}
    return render(request, 'manage_transactions.html', context)


def manage_transactions_confirm(request):
    TransactionFormSet = modelformset_factory(Transaction, fields=('chaos_number', 'status'), extra=0)
    if request.method == 'POST':
        formset = TransactionFormSet(request.POST, request.FILES)
        if formset.is_valid():
            formset.save()
            logging.info("TMP {}".format(formset))
            return render(
                template_name="manage_transactions_confirm.html",
                context={"formset": formset}, request=request
            )

    return render(template_name="base.html", context={}, request=request)


def manage_transactions_book(request):
    logging.warning("book")
    TransactionFormSet = modelformset_factory(Transaction, fields=('chaos_number', 'status'), extra=0)
    if request.method == 'POST':
        context = {
            "formset": [],  # formset because that's what they've been called since import
            "status_failed": Transaction.STATUS_FAILED,
            "n_new_failed": 0,
            "n_all_failed": 0,
            "n_new_completed": 0
        }
        formset = TransactionFormSet(request.POST, request.FILES)
        logging.debug("Booking {}".format(formset))
        for form in formset:
            logging.debug(form.instance)
            if form.instance.status == Transaction.STATUS_MATCHED_CHAOS_NR:
                form.instance.book()
                context["formset"].append(form)
                if form.instance.status == Transaction.STATUS_FAILED:
                    context["n_new_failed"] += 1
                elif form.instance.status == Transaction.STATUS_COMPLETED:
                    context["n_new_completed"] += 1

        context["n_all_failed"] = len(Transaction.objects.filter(status=Transaction.STATUS_FAILED))
        return render(template_name="success.html", context=context, request=request)

    else:
        return render(template_name="base.html", context={}, request=request)


def member_lookup(request, chaosnr):
    logging.info("member_lookup called for {}".format(chaosnr))
    try:
        member = Member.objects.get(chaos_number=chaosnr)
        return JsonResponse({
            'member_first_name': member.first_name,
            'member_last_name': member.last_name,
            'chaosnr_asked': chaosnr,
            'member_chaos_number': member.chaos_number,
            'member_paid_until': member.fee_paid_until
        })

    except Member.DoesNotExist:

        return JsonResponse({
            'member_first_name': None,
            'member_last_name': None,
            'chaosnr_asked': chaosnr,
            'member_chaos_number': None,
            'member_paid_until': None
        })

ROOT/import_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load staticfiles %}
        {% include "head_defaults.html" %}
        <title>Transaction Manager</title>
        <style>
            body{
                padding-top:70px;
            }
            #content{
                margin:2%;
            }
            .glyphicon{
                margin-left:4px;
                margin-right:6px;
            }
            .container-fluid>div {
                display:inline-block;
                vertical-align:top;
                margin:2%;
            }
        </style>
    </head>

<body>
{% include 'navbar.html' %}
        <div id="mainContainer" class="container-fluid">
        </div>
        <script src="{%  static 'js/request_helper.js' %}"></script>
        <script src="{%  static 'js/content_view.js' %}?v=1"></script>
        <script type="text/javascript" src="{%  static 'js/jquery.tablesorter.js' %}"></script>
    {% block content %}{% endblock content %}
    </body>
</html>

ROOT/import_app/templates/execute_transactions.html
{% extends "base.html" %}
{% block content %}
<h1>Transaction Manager</h1>
        {{ showme }}
        {% if message %}
           <p class="alert alert-info">
               {{ message }}
           </p>
        {% endif %}
        <!-- Upload form. Note enctype attribute! -->
        <!-- Todo: In the long run: I want to have a list of transactions ordered by rating, and the ability
        to execute through rating X. The printed chaos number and verwendungszweck, the ability to a) directly enter a
        chaos number or to click on one of the options - followed by a prompt to set score to '-1' and status to
        pending? (preferably as prefilled fields, that user can then change). I want to be able to directly execute
        one transaction. Cancel/Reject a transaction. -->
        This will be a form, where transactions can be selected based on score/flag
        {% for transaction in transactions %}
            <p>{{ transaction.chaos_number }}: {{ transaction.status }}</p>
        {% endfor %}
{% endblock %}

ROOT/import_app/templates/import_banking_csv.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <h1>Import Banking CSV</h1>

        {% if message %}
           <p class="alert alert-info">
               {{ uploadedFile }}<br>
               {{ message }}
           </p>
        {% endif %}
        {% if warnings %}
            {% for warn in warnings %}
                <p class="alert alert-warning">
                    {{ warn }}
                </p>
            {% endfor %}
        {% endif %}
        <!-- Upload form. Note enctype attribute! -->
        <form action="{% url 'import_app:import_banking' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

        <button type="button" class="btn btn-primary pull-right" onclick="window.location='{% url 'import_app:manage_transactions' %}'" >Manage Transactions</button>




            <p>{{ form.non_field_errors }}</p>
            <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>
            <p>
                {{ form.docfile.errors }}
                {{ form.docfile }}
            </p>
            <p><input type="submit" value="Upload" {% if uploadedFile != '' %} disabled {% endif %}/></p>

            {% for err in errors %}
                {{ err }}<br>
            {% endfor %}

            {% for imp in imported %}
                {{ imp }}<br>
            {% endfor %}

        </form>
    </div>
{% endblock %}

ROOT/import_app/templates/list_transactions.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

ROOT/import_app/templates/manage_transactions.html
{% extends "base.html" %}
{% block content %}
<form method="post" action="{% url 'import_app:manage_transactions' %}">
    {% csrf_token %}
    {{ formset.management_form }}
    <div class="container">
        <h2>Transactions</h2>
        <script>
function retrieve(id) {
    var lookupnrfield = document.getElementById(id);
    var value = lookupnrfield.value;
    var res = $.get('/import_app/member_lookup/'+  value);
        res.complete(function(response) {
            if (response.responseJSON != undefined){
            $('#'+id+"lookup").html(response.responseJSON.member_first_name+
                    " "+ response.responseJSON.member_last_name+
                    " ("+response.responseJSON.member_chaos_number+")");
                $('#'+id+"lookupfee").html(response.responseJSON.member_paid_until);

            }
            else{
                $('#'+id+"lookup").html("<b>UNKNOWN</b>");
                $('#'+id+"lookupfee").html("<b>UNKNOWN</b>");
            }
    });

}
        </script>

        <table class="table" id="transactions">
            <thead>
            <tr>
                <th data-toggle="tooltip" title="identified from csv"> ChaosNr</th>
                <th data-toggle="tooltip" title="lookup name from entered chaosnr"> Lookup</th>
                <th data-toggle="tooltip" title="member in db (matched by chaosnr)">Name (db)</th>
                <th data-toggle="tooltip" title="from matching member in db (matched by chaosnr)">Paid until (db
                    match)
                </th>
                <th>Status</th>
                <th data-toggle="tooltip" title="confidence score for inferred chaos nr"> Rating</th>
                <th data-toggle="tooltip" title="Referenz from csv"> Referenz</th>
                <th data-toggle="tooltip" title="Verwendungszweck from csv"> Verwendungszweck</th>
                <th data-toggle="tooltip" title="Name from csv"> Name (imported)</th>
                <th data-toggle="tooltip" title="amount from csv"> Amount (imported)</th>
            </tr>
            </thead>
            <tbody>

            {% for form in formset %}
            {% if form.instance.status == status_matching %}
            <tr class="bg-success">
                {% else %}
            <tr class="bg-danger">
                {% endif %}
                {% for field in form %}
                {% if "Id:" in field.label_tag %}
                {% else %}

                <td> {{ field }}</td>
                {% if "Chaos number:" in field.label_tag %}
                <td>
                    <button id="lookupbtn" class="btn btn-mini btn-primary" type="button"
                            onclick='retrieve("{{ field.auto_id  }}");'> lookup
                    </button>
                    {% with field.auto_id|add:"lookup" as lookupid %}
                <td>
                    <div id="{{ lookupid }}">
                        {{ form.instance.get_expected_member.first_name }}
                        {{ form.instance.get_expected_member.last_name }}
                    </div>
                </td>
                {% endwith %}
                {% with field.auto_id|add:"lookupfee" as lookupfeeid %}

                <td>
                    <div id="{{ lookupfeeid }}">{{ form.instance.get_expected_member.getPaidUntil }}</div>
                </td>

                {% endwith %}
                {% else %}
                {% endif %}
                {% endif %}
                {% endfor %}
                <td> {{ form.instance.rating }}</td>
                <td> {{ form.instance.referenz }}</td>
                <td> {{ form.instance.verwendungszweck }}</td>
                <td> {{ form.instance.payer }}</td>
                <td> {{ form.instance.amount }}</td>

                {% for hidden in form.hidden_fields %}
                {{ hidden }}
                {% endfor %}

            </tr>
            {% endfor %}

            </tbody>
        </table>

        <button class="btn btn-danger pull-right">Save Changes...</button>
        <button type="button" class="btn btn-primary pull-right"
                onclick="window.location='{% url 'import_app:import_banking' %}'">Cancel
        </button>

        <div class="pagination">
            <span class="step-links">
                {% if objects.has_previous %}
                    <a href="?page={{ objects.previous_page_number }}">Previous</a>
                {% endif %}

                <span class="current">
                    Page {{ objects.number }} of {{ objects.paginator.num_pages }}
                </span>

                {% if objects.has_next %}
                    <a href="?page={{ objects.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    </div>
</form>

<script>

    $("#transactions").one("click",function () {
        var nr = null;
        $(this).find("tr").each(function () {
            var c = 0;
            $(this).find("td").each(function () {
                var src_str = $(this).html();
                if (c == 0) {
                    var re = /value="(.*?)".*/;
                    nr = src_str.match(re)[1];
                }
                else if (c == 7) {
                    if (src_str.indexOf("<b>" + nr + "</b>") == -1) {
                    }
                    var new_str = src_str.replace(new RegExp(nr, 'g'), "<b>" + nr + "</b>");
                    $(this).html(new_str);
                }
                c++;
            });
        });
    });
</script>
<script>
        var tmp = $('select');
        $('select').on('change', function () {
            var sel = this.closest("tr");
            switch (this.value) {
                case "{{ status_matching }}": //M
                    $(sel).removeClass('bg-danger');
                    $(sel).addClass('bg-success');
                    break;
                default:
                    $(sel).removeClass('bg-success');
                    $(sel).addClass('bg-danger');
            }
        })
</script>
{% endblock %}

ROOT/import_app/templates/manage_transactions_confirm.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
    <form method="post" action="{% url 'import_app:manage_transactions_book' %}">
        {% csrf_token %}
        {{ formset.management_form }}


            <h2>Transactions CONFIRM</h2>

<button type="submit" class="btn btn-danger pull-right">Book transactions</button>
        <button type="button" class="btn btn-primary pull-right" onclick="window.location='{% url 'import_app:import_banking' %}'" >Cancel</button>
            <table class="table">
                <thead>
                <tr>
                    <th>ChaosNr</th>
                    <th>Status</th>
                    <th>Rating</th>
                    <th>Info</th>
                </tr>
                </thead>
                <tbody>

                {% for form in formset %}
                    {% if form.instance.status in status_matching %}
                    <tr>

                        <td> {{ form.instance.chaos_number }}</td>
                        <td> {{ form.instance.status }}</td>
                        <td> {{ form.instance.rating }}</td>
                        <td> {{ form.instance.information }}</td>

                    </tr>
                    {% endif %}
{% for hidden in form.hidden_fields %}
    {{ hidden }}
{% endfor %}
                {% endfor %}

                </tbody>
            </table>



    </form>
    </div>
{% endblock %}

ROOT/import_app/templates/success.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <a type="button" class="btn btn-primary pull-left" onclick="window.location='/'">AA Home</a>
    <a type="button" class="btn btn-primary pull-right" onclick="window.location='{% url 'import_app:manage_transactions' %}'" >Manage Transactions</a>
    <a type="button" class="btn btn-primary pull-right" onclick="window.location='{% url 'import_app:manage_transactions_failed' %}'" >Manage Failed Transactions</a>
                <table class="table">
                <thead>
                <tr>
                    <th>ChaosNr</th>
                    <th>Status</th>
                </tr>
                </thead>
                <tbody>
    <table class="table">
        <tr><th>Completed Transactions</th><th>{{ n_new_completed }}</th></tr>
        <tr><th>Failed Transactions</th><th>{{ n_new_failed }}</th></tr>
        <tr><th>Total Failed in DB</th><th>{{ n_all_failed }}</th></tr>
    </table>

       <table class="table">
       <thead>
       <tr>
           <th>ChaosNr</th>
           <th>Status</th>
       </tr>
       </thead>
       <tbody>

       {% for form in formset %}

           <tr>

               <td> {{ form.instance.chaos_number }}</td>
               {% if form.instance.status == status_failed  %}
                   <td class="alert alert-danger"> {{ form.instance.status }}</td>
               {% else %}
                   <td> {{ form.instance.status }}</td>
               {%  endif %}
           </tr>

       {% endfor %}

       </tbody>
   </table>

</div>
{% endblock %}